##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Run this file by executing "liquibase flow" or "liquibase flow --flow-file=liquibase.flowfile.yaml"

stages:

  Status Database:
    actions:
      - type: liquibase
        command: status
        cmdArgs: {verbose: "true"}

  DB_Deployment:
    actions:
      - type: liquibase
        command: tag
        cmdArgs: {tag: "${TAG}"}
      - type: liquibase
        command: update

## The endStage ALWAYS RUNS. 
endStage:
  actions:
    - type: liquibase
      command: history
